[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ten_utils"
version = "0.1.0"
description = "A toolkit for reuse"
authors = [{ name = "Караваев Александр", email = "234iskateli234@gmail.com" }]
license = { file = "LICENSE" }
dependencies = []